---
title: "Data Types"
output:
  html_document:
    code_folding: show
---

```{r echo=FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      comment = NA)
```

When we talk about data, we can talk about data types, data classes, and data structures.

## Types

Data types are fundamental building blocks for storing information. Below, we can see a chart of all of the datatypes in Python.

#### Datatypes

| <span style="color:lightBlue">English name</span>  | <span style="color:lightBlue">Type name</span>  | <span style="color:lightBlue">Description</span>   | <span style="color:lightBlue">Example</span>  |
| :---         | :---:     | :---:                           | ---:    |
|integer       |**int**        |positive/negative whole numbers   |<span style="color:green">13</span>       |
|floating point number|**float** |real number in decimal form     |<span style="color:green">3.1415</span>|
|boolean       |**bool**        |true or false                    |<span style="color:green">True</span>|
|string        |**str**         |text                             |<span style="color:green">"Do you like Python?"</span>|
|list          |**list**        |a collection of objects - mutable & ordered |<span style="color:green">['Hi','Hello','Hola']</span>|
|tuple         |**tuple**       |a collection of objects - immutable & ordered|<span style="color:green">('Tuesday',3,14,2023)</span>|
|dictionary    |**dict**       |mapping of key-value pairs       |<span style="color:green">{'name':'Madison','Program':'Data Science','Age':23}</span>|
|none          |**NoneType**    |represents no value              |<span style="color:green">None</span>|


:::note

Character data, also known as strings, are always wrapped in "quotation marks". You can use single quotes like 'this' or double quotes like "this". As long as you use two of the same, it doesn't matter which you use!

:::

We can use the function `type()` to view the datatype of the stored value in a variable. Let's explore a few examples of this.

```{python}
# Datatype 
x = 1 + 1
type(x)
``` 

```{python}
x = 2.0
type(x)
```

```{python}
# String
string = 'Okanagan'
print(string)
type(x)
```
## Comparison Operators

We can compare objects (or variables) using comparison operators. The result is a Boolean value. Recall from above that a Boolean gives either a True or False.

First, let's look at a table of the different comparison operators.

#### Comparison Operators

|<span style="color:blue">Operator</span> | <span style="color:blue">Description</span> |
| :--- | :--- |
|<span style="color:green">x == y</span>|is <span style="color:green">x</span> equal to <span style="color:green">y</span>?|
|<span style="color:green">x != y</span>|is <span style="color:green">x</span> not equal to <span style="color:green">y</span>?|
|<span style="color:green">x > y</span>|is <span style="color:green">x</span> greater than <span style="color:green">y</span>?|
|<span style="color:green">x >= y</span>|is <span style="color:green">x</span> greater than or equal to <span style="color:green">y</span>?|
|<span style="color:green">x < y</span>|is <span style="color:green">x</span> less than <span style="color:green">y</span>?|
|<span style="color:green">x <= y</span>|is <span style="color:green">x</span> less than or equal to <span style="color:green">y</span>?|
|<span style="color:green">x is y</span>|is <span style="color:green">x</span> the same object as <span style="color:green">y</span>?|
|<span style="color:green">x and y</span>|are <span style="color:green">x</span> and <span style="color:green">y</span> both true?|
|<span style="color:green">x or y</span>| is at least one of <span style="color:green">x</span> and <span style="color:green">y</span> true?|
|<span style="color:green">not x</span>| is <span style="color:green">x</span> false? |

Now, let's look at a few examples.

```{python}
5 < 7
```

```{python}
five = 5
seven = 7
five < seven
```

```{python}
5.0 == 5
```

```{python}
5.0 == '5'
```


## Lists

Lists are an important tool used in Python. Lists can contain elements of mixed types as well. Let's look at a few examples.

```{python}
# List
list1 = []
list1
```

```{python}
list2 = [1, 'UBC', 100]
list2
```

Now let's see a few operations we can perform on a list.

```{python}
len(list1)
```

```{python}
len(list2)
```

```{python}
# Indexing Example - we will talk more about this later on
list2[2]
```
Note - Python indexing starts at zero, so the first element in the list is 0, the second is 1, and the third is 2, so if we actually wanted the second element, we would have to do this:

```{python}
list2[1]
```

```{python}
type(list2)
```

```{python}
type(list2[1])
```

:::exercise

Create a list that contains an integer, float, Boolean value, and string. Make sure to save it to a variable. Then, practice indexing each element individually. Check the type of the list itself, and then each element individually.

:::

:::solution

```{python, class.source = 'fold-hide'}
mixed_list = [13, 3.14, True, 'UBC']
mixed_list[0]
mixed_list[1]
mixed_list[2]
mixed_list[3]
type(mixed_list)
type(mixed_list[0])
type(mixed_list[1])
type(mixed_list[2])
type(mixed_list[3])
```

:::

As we mentioned earlier, a main difference between lists and tuples is that lists are mutable. Mutable means that elements in a list can be appended, changed, or deleted. 

```{python}
mixed_list.append('New')
mixed_list
```
If we decided that we wanted to replace 'New' with 4, we could do so like this:

```{python}
mixed_list[4]= 4
mixed_list
```
If we wanted to remove elements from the list, we could do so like this:

```{python}
mixed_list.remove('UBC')
mixed_list
```

Note that this will only remove the first occurrence, if this happened to be in the list more than once. It would also call an error message if the element doesn't exist.

If we wanted to remove it based on the index of the list:

```{python}
del mixed_list[0]
mixed_list
```

:::exercise

Create an empty list. Try adding an element to the list, and then deleting it, either by using `remove` or `del`.

:::

:::solution

```{python, class.source = 'fold-hide'}
empty_list = []
empty_list.append(5)
empty_list

empty_list.remove(5)
empty_list
```

Alternatively,

```{python, class.source = 'fold-hide'}
empty_list = []
empty_list.append(5)
empty_list

del empty_list[0]
empty_list
```

:::

## Dictionaries

A dictionary lists key-value pairs, which could also be thought of as associated values where a key matches to the associated value. Let's look at a few examples.

```{python}
# Dictionary - mapping between values
house = {'bedrooms': 3, 'bathrooms': 2, 
         'city': 'Kelowna', 'price': 250000}
```


```{python}
house['price']
```


```{python}
course = {'Data Science': ['DATA100', 'DATA200', 'DATA300'],
            'Science': ['SCIENCE100', 'SCIENCE200', 'SCIENCE300']}
```


```{python}
course['Data Science']
```

:::exercise

Turn the following information into a dictionary. Don't forget to save it as a variable!

Name | ID | Campus | Courses
--- | --- | --- | ---
Dan | 12345678 | Okanagan | DATA100, ENGL100, HIST100, CHEM100

:::

:::solution

```{python, class.source = 'fold-hide'}
student = {'Name' : 'Dan',
            'ID' : 12345678,
            'Campus' : 'Okanagan',
            'Courses': ['DATA100', 'ENGL100', 'HIST100', 'CHEM100']}
student
```

:::



## Loops

Loops are a common tool used in Python to help users iterate through lists, or perform the same operation numerous times without added efforts.

Let's look at a few examples:

```{python}
# Loops

for n in [0, 1, 5, 2, -5]:
    # this is inside the loop
    print("The number is", n, "and its squared value is", n**2)
# this is outside the loop
```

```{python}
## Loop
s = "Python"
for c in s:
    print(c + "!")
```

```{python}
# range(10) sets values 0-9, because recall Python starts at 0, not 1
for i in range(10):
    print(i)
```

This is equivalent to writing:

```{python}
for i in range(0,10):
    print(i)
```

If we wanted it to start at 1 and go to 10 (inclusive), we would write:

```{python}
for i in range(1,11):
    print(i)
```

Other examples:

```{python}
#(start,end,increments)
for i in range(0,101,10):
    print(i)
```

```{python}
n = 3
while n > 0:
    print(n)
    n = n - 1

print("Smile!")
```

## Data Frames

A data frame essentially functions as a series of connected vectors or lists, where each vector or list is a column. In this sense a data frame is also a special kind of list.

In a data frame, all vectors need to be of the same length. And while each vector must hold the same data type, not all vectors need to be of the same data type. Data frames also allow us to apply column names.

Let's look at an example of creating a dataframe from two lists.

```{python}
letter_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']
number_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
import pandas as pd
df = pd.DataFrame(
    {'Letters': letter_list,
     'Numbers': number_list})

df
```

Alternatively, you could write a data frame directly like this:

```{python}
df1 = pd.DataFrame({'x' : [1., 2., 3., 4.],
                   'y' : [4., 3., 2., 1.],
                   'z' : [1, 2, 3, 4]})
df1
```

Data frames are a VERY powerful data type in Python. We will spend most of our remaining time working with data frames because there is so much to learn about. 

:::exercise

Using whichever method you prefer, turn the following information into a data frame.

Name | ID | Campus 
--- | --- | --- 
Dan | 1234 | O 
Sam | 5678 | V 
Jim | 9012 | V 
Matt | 3456 | O 

:::

:::solution

Method 1
```{python, class.source = 'fold-hide'}
students = pd.DataFrame({'Name' : ['Dan', 'Sam', 'Jim', 'Matt'],
                   'ID' : [1234, 5678, 9012, 3456],
                   'Campus' : ['O', 'V', 'V', 'O']})
students
```

Method 2
```{python, class.source = 'fold-hide'}
names = ['Dan', 'Sam', 'Jim', 'Matt']
IDs = [1234, 5678, 9012, 3456]
campuses = ['O', 'V', 'V', 'O']

students2 = pd.DataFrame(
    {'Name': names,
     'ID': IDs,
     'Campus': campuses})

students2

```

:::

Note: Think about what the difference would be if you entered the ID numbers as strings rather than integers.