---
title: "Getting Started"
output:
  html_document:
    code_folding: show
---

```{r echo=FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      comment = NA)
```


In this workshop, we will be using Python via Jupyter Notebook. To use this, you will need to use your UBC login information and head to this [link ](https://ubc.syzygy.ca/). Click the 'Sign in' button on the top right.

## Some Basic Syntax

Syntax is the rules that define the combination and order of symbols in a computer language.

```{python}
# Intro to Python

### this is a comment - it is not visible by the code, 
# and it helps with readability
```

#### Python can be used as a calculator

```{python}
1 + 1
```

```{python}
2-3
```

```{python}
6 / 2
```

```{python}
3 * 4
```

Since Python is so widely used, there are many people who contribute to continuously improving and developing it. Let's imagine Python as a base version. It can do basic calculations, but it requires extra efforts to do more complicated things. People have created extras or add-ons to help create shortcuts for more complicated specific tasks or functions. These 'add-ons' are called packages. Packages can be imported to use to help make things easier. For example, there is a Python package called math that helps with basic mathematical operations. Let's look at an example here of calling the package using the ```import``` command.

```{python}
import math
math.sqrt(9)
```

Once it has been imported, it does not need to be re-imported for the rest of this document. You can also import multiple packages within the same document. We will get into more useful packages later on!

```{python}
math.log(100)
```

Python can also string numbers together through a range. The range function consumes the variables range(start, end, step)

```{python}
x = range(6)
for n in x:
  print(n)
```

```{python}
for n in range(10, 100, 10):
  print(n)
```

:::exercise

Calculate the result of `3 + 2 * 6`, calculating the addition before multiplication

Take the square root of `20 * 5`

Calculate the log of 16

Take the square root of the numbers 1 through 10

:::

:::solution

```{python, class.source = 'fold-hide'}
(3 + 2) * 6 # note python automatically will follow the order of operations

math.sqrt(20 * 5)

math.log(16)

for i in range(1,11):
  print(math.sqrt(i))
```

:::