---
title: "Loading Data"
output:
  html_document:
    code_folding: show
---

We're going to work with a data set today, which we won't even have to download. We are going to access this data set through a URL which will save on storage.

:::note

* See the data here: https://raw.githubusercontent.com/jstaf/gapminder/master/gapminder/gapminder.csv

:::

First things first, we need to use the trusty pandas package. This is the go-to Python package for data frames and data set analysis. We will talk about packages more later on.

```{python}
import pandas as pd # we nickname it pd to save time when calling it later
```

We can enter the URL to the data set and save it as a variable so that it is easily accessible. Since the data set is a `.csv` file, we can use the pandas function `read_csv()` to save the data into a data frame!

```{python}
url = 'https://raw.githubusercontent.com/jstaf/gapminder/master/gapminder/gapminder.csv'
df = pd.read_csv(url)
```

The `head()` function is often used to show the first few rows of a data frame. The default is the first five rows, but you can enter a different value inside the brackets to get the first n number of rows.

```{python}
df.head()
```

But if we only wanted to see the first 3 rows....

```{python}
df.head(3)
```

Remember, Python starts at 0 and not 1, so the first row of data is technically zero! Also, notice that pandas noticed that the first row of the csv file was header names, so it automatically created column titles.

We can also do this for the last few rows of the data set, know as the tail.

```{python}
df.tail()
```

We can now explore the data a bit more, looking at the data types and data structures.

We can use the `.info()` function to get a summary of data frame information, such as the count of null values, data types, etc. Take a look below.

```{python}
df.info()
```

We can also quickly see summary statistics using the `.describe()` function.

```{python}
df.describe()
```

If we wanted to know the number of unique values of a specific column, we could use the `value_counts()` function.

```{python}
df.country.value_counts()
```
This shows that there are 12 occurrences of each unique country value.

::: exercise

If we wanted to know the number of countries recorded for each year, how would we find that information?

Hint: Very similar to the most recent example above.

:::

:::solution

```{python, class.source = 'fold-hide'}
df.year.value_counts()
```

:::

If we wanted to find specific values, let's say the maximum values, we could use the function `.max()`.

```{python}
df.max()
```

Other similar functions include `.min()`, `.mean()`, and `.median()`.

If we wanted to group by specific data, let's say country, and then apply an aggregate function, we could do it like this:

```{python}
df.groupby('country').max()
```

We can also group by multiple columns.

```{python}
df.groupby(['country', 'year']).max()
```

Note that because we are grouping by country and year, there is only one value for each variable, so the max function will show the same as `.min()` or `.mean()`, etc.


::: exercise

If we wanted to know the number of countries in each continent recorded for each year, how would we find that information?

Hint: Try grouping by year, and then using the `value_counts()` function with continent.

:::

:::solution

```{python, class.source = 'fold-hide'}
df.groupby(['year']).continent.value_counts()
```

:::



Next, we'll take a step back and talk about packages.