---
title: "Functions"
output:
  html_document:
    code_folding: show
---

```{r echo=FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      comment = NA)
```

Functions take in data and do things with that data. We can write our own functions, but generally in Python we'll be using functions that have already been written or built. You've already seen the functions, `math.sqrt()` and `math.log()`.

Calling a function requires 2 things: the function itself and any arguments the function allows us to specify -- one of these arguments is the data source, but there are usually other parameters we can specify.

## Descriptive Stats

We'll explore the basics of a handful of functions for descriptive stats with a randomized set of data. We can generate a random list of data using a package called random.

```{python}
import random
#Generate 50 random numbers between 10 and 200
randomlist = random.sample(range(10, 200), 50)
print(randomlist)
```

To calculate the mean of this data, we use the function `mean()` which is a part of the package numpy

```{python}
import numpy as np
np.mean(randomlist) # calculate the mean 
```

Alternatively, the mean could also be calculated with this:

```{python}
sum(randomlist) / len(randomlist) # calculate the mean
```

For the median,

```{python}
import statistics as st
st.median(randomlist) # calculate the median
```

The statistics and numpy package are very useful for computing functions.

But we can calculate the variance and standard deviation using NumPy again,

```{python}
np.var(randomlist) # variance
```

```{python}
np.std(randomlist) # standard deviation
```

## Arguments

So far, the only 'argument' we've passed to any of these functions is the data itself.

:::note

Other functions to create random samples include `random.uniform()` for uniformly distributed data and `random.normal()` for normally distributed data.

:::

:::summary

Functions are mini programs that do things with our data. They generally have parameters, or arguments, that can be specified to customize how the function operates. 

:::

:::functions

| Function | Description |
| :--- | :--- |
| `mean` | calculate the mean of a range of values. |
| `median` | calculate the median of a range of values. |
| `var` | calculate the variance of a range of values. |
| `std` | calculate the standard deviation of a range of values. |
| `sample` | take a random sample from a range of values. |

:::