---
title: "R & RStudio"
output:
  html_document:
    code_folding: show
---

```{r echo=FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      comment = NA)
```

## What is Python

Python is a general programming language used to create many different programs. It is often used to build websites, conduct data analysis, and automate tasks. It is an object-oriented language, meaning that different objects are defined with different attributes and properties. It is often used to facilitate statistical analysis and generate graphs. Python is also the program that converts what we write or input into something your computer can execute.

Python is the second most widely used programming language in 2022, only behind Java. Knowing basic Python can open up many job opportunities in a variety of industries, for virtually any background. Did you know that YouTube (owned by Google) is written mostly in Python? How about Instagram? Reddit? Pinterest?

In academia, Python is widely used in data science and computer science. It is also used in a lot of research in a variety of subject areas, including the humanities, sciences, and engineering. Python is also great for sentiment analysis, which is when language or text is processed.

Speaking of text, let's see how we print a line of text in Python.

```{Python}
print("Hello World!")
```

## Jupyter Notebook

Jupyter Notebook is a web-based interactive computing platform, and it can be used for many things, aside from Python.

Think of Python as the language you are writing in, and Jupyter as the pen and pencil. This is how Python and Jupyter are used together.


:::note

There are many different IDEs (integrated development environment) for Python. To name a few, [Programiz](https://www.programiz.com/python-programming/online-compiler/), Atom, Visual Studio Code, Spyder, and many more. If anyone has trouble with the Jupyter install, try using Programiz, as it doesn't require any downloads.

:::

## Building Blocks

The big difference with working in something like Python, over say Excel or another point and click tool for working with data, is that it moves us into the realm of programming, which brings with it a need to understand some core concepts about how data are handled and stored by computers.

While we're not outright programming, we will be writing scripts to do things with our data --and basically, that's what a program is -- data, and a series of instructions--functions--to do things with these data.

## How it Works

1. You write instructions
2. You give those instructions some data
3. A compiler converts those instructions to something you computer can execute
4. Your computer executes those instructions on your data
5. You get the results presented to you, either on your screen, stored to a file, sent to a printer etc.