---
title: "Getting Help"
output:
  html_document:
    code_folding: show
---

```{r echo=FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      comment = NA)
```

There are several ways to get help with Python.

## Built in Help

In general, packages and their functions and data are pretty well documented.

There are many ways to access this documentation from within Python.

We follow the syntax `help([object])` to call the help documentation.

We can see an example of this with the print function.

```{python}
help(print)
```

## Blogs, Tutorials & Forums

Millions of people all over the world use Python, and it's likely that if you're having a problem, someone else has come across that problem too. There are many blogs and forums where people share their problems and crowd source solutions! It is a great tool for others to learn from and share their knowledge and tips.

As a new user, they can also be a bit confusing. This is partly because there are many ways to solve the same problem when programming, so you’ll likely see lots of different approaches, some of which are more familiar to you than others. The other is that Python supports multiple syntaxes; that is, multiple ways of expressing or constructing the arguments that one puts together. This is kind of an unusual feature and as a result, you may see a solution that uses a different syntax than you’re used to.

The key here is to spend time reading blogs and forum responses and working your way through problems; the proposed solutions will start to make more sense with time and familiarity, just like learning any other language.

The easiest portal to these resources is Google or a similar search engine.
